from prompts.correction_prompt import (
    CORRECTION_PROMPT,
)


def correction_agent(
    llm,
    user_query,
    planner_result,
    tool_result,
    retrieved_context,
    previous_response,
    evaluation_feedback,
):
    """
    Correct the response generated by the Response Agent.
    """

    prompt = f"""
{CORRECTION_PROMPT}

User Query:
{user_query}

Planner Result:
{planner_result}

Tool Result:
{tool_result}

Retrieved Context:
{retrieved_context}

Previous Response:
{previous_response}

Evaluation Feedback:
{evaluation_feedback}
"""

    response = llm.invoke(prompt)

    return response.content